import { Context } from "./context";
import { IpsEmitterOptions } from "./model/ips-emitter-options";
import { IpsCoordinates } from "./model/ips-coordinates";
import { MinMax } from "./model/min-max";
export declare class ParticleEmitter {
    private context;
    private options;
    private width;
    private height;
    private length;
    private index;
    private startPosition;
    private velocity;
    private startTime;
    private lifeTime;
    private size;
    private growth;
    private renderer;
    private renderCall;
    private updateParticles;
    private deltaLeft;
    private particlesSec;
    private renderMode;
    private positionType;
    private lifeTimeOption;
    private color;
    private alpha;
    startOption: IpsCoordinates;
    private _startOption;
    velocityOption: IpsCoordinates;
    private _velocityOption;
    growthOption: number;
    private _growthOption;
    sizeOption: MinMax<number>;
    textureKey: string;
    blendmodeSource: number;
    blendmodeTarget: number;
    constructor(context: Context, options: IpsEmitterOptions, width: number, height: number);
    private setOptions(options);
    setColor(colorHex: string): void;
    update(delta: number): void;
    render(time: number): void;
    private initPool(particlesSec, lifetime, growth);
    private generateParticles(nrOfParticles);
    private setParticleValues(startTime);
    private setTimeValue(startTime);
    private rand(min, max);
}
